# Generated by Django 5.0.3 on 2024-04-21 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lst_app', '0002_alter_feedback_user_alter_program_organizers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lst_app.customuser'),
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lst_app.customuser'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lst_app.customuser'),
        ),
        migrations.AlterField(
            model_name='program',
            name='organizers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lst_app.customuser'),
        ),
        migrations.AlterField(
            model_name='program_registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lst_app.customuser'),
        ),
    ]
