# Generated by Django 5.0.3 on 2024-04-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lst_app', '0003_alter_attendance_user_alter_event_registration_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accomodation_dates',
            field=models.ManyToManyField(blank=True, to='lst_app.accomodation_date'),
        ),
    ]
