# Generated by Django 5.0.3 on 2024-05-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lst_app', '0004_event_accomodation_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='organizers',
        ),
        migrations.AddField(
            model_name='program',
            name='organizers',
            field=models.ManyToManyField(blank=True, to='lst_app.customuser'),
        ),
    ]
